### PR TITLE
Feature/travis ci linux osx

### PR DESCRIPTION
**Pull request by michelp**

### CODE REVIEW

**Comment by DrTimothyAldenDavis** [comment]
You can now pass CMAKE_OPTIONS="-DGBCOMPACT=1" to cmake, via the top-level makefile, as (for example):

JOBS=8 CMAKE_OPTIONS="-DGBCOMPACT=1" make

**Comment by michelp** [comment]
@szarnyasg @DrTimothyAldenDavis moving the GBCOMPACT discussion to here.

Got the linux build under 4 minutes on Travis using the compact option:

https://travis-ci.org/michelp/LAGraph/builds/657592964

osx is failing, but i've marked it as optional, and it fails fast.  it throws a lot of unrecognized warning group warnings.

**Comment by michelp** [comment]
> You can now pass CMAKE_OPTIONS="-DGBCOMPACT=1" to cmake, via the top-level makefile, as (for example):
> 
> JOBS=8 CMAKE_OPTIONS="-DGBCOMPACT=1" make

Is that backported to 3.2.0?

**Comment by szarnyasg** [comment]
I copied this branch to my fork and merged it with `master` -- the `.travis.yml` file had some conflict, I resolved those and worked on refining the CI configuration: https://github.com/szarnyasg/LAGraph/tree/feature/travis-ci-linux-osx
The OS X build now starts and fails at a later stage. Looking into it.

**Comment by szarnyasg** [comment]
Okay, the OS X build almost works now. Problems that remain:

- The log is massive due to a large number of warnings. 
- Tests in the `Complex directory` fail.

Raw log: https://api.travis-ci.org/v3/job/657795742/log.txt (I'd recommend `wget`ting it instead of opening it in the browser).

**Comment by DrTimothyAldenDavis** [comment]
It doesn't like this, in complextest.c:

#define LL CMPLX(1,1)

Maybe try

#define LL (CMPLX(1.0,1.0))

instead.  I've seen that before, I think.

**Comment by szarnyasg** [comment]
I pushed this fix but it did not fix the problem. Raw log: https://api.travis-ci.com/v3/job/293475824/log.txt

**Comment by szarnyasg** [comment]
@michelp Fantastic, the build is green for both OSs and tests run just fine.

One idea for improving the CI scripts: it's possible to get rid of `ldconfig` by using `cmake` which, when building `LAGraph`, produces a Makefile that looks for GraphBLAS in `../GraphBLAS/Include`.

See my `.travis.yml`: https://github.com/szarnyasg/LAGraph/blob/feature/travis-ci-linux-osx/.travis.yml

**Comment by szarnyasg** [comment]
I'm tweaking mine a bit more, results should come in 10 minutes from now. N.b. you don't actually need `make install` as it will discover the files in the `../GraphBLAS/Includes` directory.

**Comment by szarnyasg** [comment]
I've created a .travis.yml file that should work but now Travis does not start a build...
https://github.com/szarnyasg/LAGraph/blob/feature/travis-ci-linux-osx2/.travis.yml

**Comment by michelp** [comment]
The tests weren't finding GraphBLAS.h, which I was hoping make install would fix.

Travis should provide an evolutionary algorithm that just twiddles all these knobs till it works :)

**Comment by szarnyasg** [comment]
Take a look at https://github.com/szarnyasg/LAGraph/blob/04c8968e355b8e6d1fb2c855472f571505568e87/.travis.yml and its build at https://travis-ci.org/szarnyasg/LAGraph/builds/657883881

**Comment by szarnyasg** [comment]
> the build is green for both OSs and tests run just fine.
Correction, it seems that the Mac was (and is) broken due to errors around complex.

**Comment by szarnyasg** [comment]
I've added a `-w` flag to the `CMAKE_C_FLAG`. This does not solve the problem but significantly shortens the output log so that it does not freeze the browser for several seconds.
https://travis-ci.org/szarnyasg/LAGraph/jobs/657899922

**Pull request closed without merging**
