### PR TITLE
LCC optimizations and bugfixes

### LINKED ISSUE #81: Optimize LAGraph_lcc
[`LAGraph_lcc`](https://github.com/GraphBLAS/LAGraph/blob/master/Source/Algorithm/LAGraph_lcc.c) could greatly benefit from the tricks emloyed in [`LAGraph_tricount`](https://github.com/GraphBLAS/LAGraph/blob/master/Source/Algorithm/LAGraph_tricount.c), namely, using the `GxB_PLUS_PAIR_INT64` semiring (to avoid looking into the values of the matrices under multiplication) and the `GrB_DESC_S` or similar descriptor (to avoid looking into the values in the mask).

### PR DESCRIPTION
**Pull request by szarnyasg**
Fixes #81. Tested with Graphalytics, which it passed on M1:

```console
10:27 [INFO ] [BenchmarkRun [r694234, LCC[none], graph500-22, timeout=900s]] => succeed, T_l=22.397s, T_m=124.552s, T_p=119.853s.
10:27 [INFO ] [BenchmarkRun [r472882, LCC[none], graph500-22, timeout=900s]] => succeed, T_l=22.397s, T_m=126.412s, T_p=121.648s.
10:27 [INFO ] [BenchmarkRun [r763736, LCC[none], graph500-22, timeout=900s]] => succeed, T_l=22.397s, T_m=133.389s, T_p=128.698s.
10:27 [INFO ] [BenchmarkRun [r796493, LCC[none], dota-league, timeout=900s]] => succeed, T_l=15.596s, T_m=178.147s, T_p=177.879s.
10:27 [INFO ] [BenchmarkRun [r694345, LCC[none], dota-league, timeout=900s]] => succeed, T_l=15.596s, T_m=176.347s, T_p=176.080s.
10:27 [INFO ] [BenchmarkRun [r638649, LCC[none], dota-league, timeout=900s]] => succeed, T_l=15.596s, T_m=186.822s, T_p=186.550s.
10:27 [INFO ] [BenchmarkRun [r610148, LCC[none], datagen-7_5-fb, timeout=900s]] => succeed, T_l=12.645s, T_m=11.697s, T_p=10.326s.
10:27 [INFO ] [BenchmarkRun [r472974, LCC[none], datagen-7_5-fb, timeout=900s]] => succeed, T_l=12.645s, T_m=11.917s, T_p=10.171s.
10:27 [INFO ] [BenchmarkRun [r885364, LCC[none], datagen-7_5-fb, timeout=900s]] => succeed, T_l=12.645s, T_m=11.727s, T_p=10.359s.
```

### CODE REVIEW

**Comment by szarnyasg** [comment]
This is mysterious. It passes locally on my M1 CPU but it fails in CI on both Linux and MacOS – both run on an Intel CPU.

The test case that fails is `lcc_test` with matrix `west0067.mtx`. However, the printed results are same, the difference is in the `err` value:

Ran on M1:
```console
================================== west0067.mtx:

lcc (known result, but with float precision):
GrB_FP64 vector: n: 67 entries: 67
[...]
err: 4.44444e-07
```

Ran on Intel:
```console
================================== west0067.mtx:

lcc (known result, but with float precision):
GrB_FP64 vector: n: 67 entries: 67
[...]
err: 0.053571
[ FAILED ]
  Case west0067.mtx:
    test_lcc.c:184: Check err < 1e-6... failed
```

**Comment by szarnyasg** [comment]
Curiously, the builds using `vanilla` mode pass, see the CI output.

Screenshot 2023-03-31 at 12 05 45
(The one that didn't pass was cancelled due to other jobs failing.)

I could also reproduce this locally.

**Comment by DrTimothyAldenDavis** [comment]
I'll take a look.

**Comment by DrTimothyAldenDavis** [comment]
I've replicated the error in my current master branch (v8.0.0.draft4, running with debug on and in the new COMPACT mode.  My JIT is on but I don't think that effecting the results because I'm seeing the same error you're seeing)  Valgrind is reporting some errors, where a matrix freed by LAGraph_lcc is being freed again somewhere else.  I'm guessing there's a bug in lcc, or the test for lcc, with a double-free that somehow was not causing a problem until now.

The vanilla tests pass because the lcc tests require SuiteSparse.  If LAGRAPH_SUITESPARSE is false, lcc isn't tested at all.

**Comment by DrTimothyAldenDavis** [comment]
In particular, valgrind complains about a double-free when just running the first matrix of size 7, even though the tests pass just fine with just that one matrix.

**Comment by DrTimothyAldenDavis** [comment]
Oh ... I see it.  It's a bug in LAGraph_lcc.

The input matrix is A, and it's const.  It of course should not be modified.  But with sanitize false, S=A is done.  Then if C is symmetric, we do "C = S ; S = NULL ; "  So C is the same as A.  Then at the end, LG_FREE_ALL frees C ... which is thus the input matrix A.

So it's a memory corruption.  Somehow this was passing the tests before, and a tiny tweak triggered a failure.  The bug has been there a while I think.

**Comment by DrTimothyAldenDavis** [comment]
There are two kinds of bugs.  I fixed the memory leaks but the error remains.  The U matrix is not iso-valued; it contains entries equal to 2 in some places.  So the PLUS_TIMES and PLUS_ONE semirings will give different results.

The problem is the construction of D=A+A' when A is unsymmetric Or maybe that isn't a problem ... because it is said to be a multigraph in the comments.  That means D has entries that can be 1 or 2, since S is supposed to be binary with no self edges.  Then U = triu(D) is computed, so U has entries equal to 1 or 2.

Then CL<C> = C*U' is computed.  That must use the PLUS_TIMES semiring; or at least it should if A is unsymmetric.  The PLUS_ONE semiring will give the wrong answer I think.

Maybe we should look at the code together over zoom sometime.  I'll post my memory fixes.

**Comment by szarnyasg** [comment]
I implemented the suggestions discussed yesterday in the LAGraph meeting. The algorithm now uses FP64 consistently to avoid typecasts (there's no `generic` in the burble anymore) and it leverages iso-valued matrices/vectors.

This PR is ready for review now.

**Comment by pcostanza** [comment]
Hi Gabor.
I have just submitted a PR that streamlines the stable LCC code and makes it better testable. There is now a simple algorithm, so all test cases can be compared against a baseline. Maybe this helps with your PR.

The sanitization logic was not correct and failed for ldbc-undirected-example.mtx. The issue is that it contains floating point numbers all < 1. The check whether to sanitize or not is based on whether the graph has any self edges or not. That file doesn’t have any self edges, so the matrix doesn’t get sanitized. However, in a later stage of the computation, the matrix is converted from GrB.Matrix[float64] to GrB.Matrix[uint32] (U), and that causes all entries to be rounded down to 0.

One aspect of the sanitize step is that the input matrix gets converted to a Boolean representation. Since that doesn’t happen, later computations use 0 instead of 1 for multiplication, and that causes the final result to be wrong. When I force sanitization, it works out. The test for sanitization turned into (G->nself_edges != 0) || (strcmp(aname, "ldbc-undirected-example.mtx") == 0), which is of course a hack.

I hope you find this helpful.

Pascal

**Comment by szarnyasg** [comment]
Superseded by #185.

**Pull request closed without merging**
