### PR TITLE
Feature/complete complex operators

### LINKED ISSUE #62: Completing LAGraph_Complex with operators from SuiteSparse usercomplex
In pygraphblas I've wrapped both LAGraph_Complex and the usercomplex example from SuiteSparse, thus providing two complex types, but i'd like to consolidate them down to LAGraph_Complex.  LAGraph_Complex only defines a few operations based on need in the algorithms, usercomplex provides a more complete set of complex operations like add, multiply, equality, etc.  Before I start on this work I wanted to raise this issue to make sure that merging the usercomplex operations into LAGraph is a desirable approach.

### PR DESCRIPTION
**Pull request by michelp**
This is a preliminary work for code review.  Fixes #62

### CODE REVIEW

**Comment by DrTimothyAldenDavis** [comment]
Why the need for "do {  ... } while (0) ;" around some of the macros?

**Comment by michelp** [comment]
Mostly habit to turn the compound block into a single statement:

https://stackoverflow.com/questions/1067226/c-multi-line-macro-do-while0-vs-scope-block

In this case i guess it's not required and i can remove it.

**Comment by michelp** [comment]
@DrTimothyAldenDavis Something I wanted to get explicitly from you is permission to relicense the usercomplex code into LAGraph, the two are under difference licenses.  I think just positively affirming the relicense is ok here in a comment is fine.

**Comment by DrTimothyAldenDavis** [comment]
Yes -- you can use usercomplex under either license.

**Comment by DrTimothyAldenDavis** [comment]
I would prefer not to have the "do { ... } while (0)" ... it looks a little
confusing to me.

**Comment by michelp** [comment]
Already gone :)

**Comment by michelp** [comment]
Sounds good, I'll make the change today.  I assume this also means changing the names of all the operators to *_ComplexFP64 as well.  

I didn't realize complex integers was even a thing, but I guess it is!

https://en.wikipedia.org/wiki/Gaussian_integer

**Comment by michelp** [comment]
> I'm considering adding complex floating point types (single and double) as GxB_* built-in types to GraphBLAS, in the future. Mainly because MATLAB now has all of these data types.

That got me thinking, should I make these changes as a PR to SuiteSparse instead?  You've already got all the templates in place.

**Comment by DrTimothyAldenDavis** [comment]
You mean to SuiteSparse:GraphBLAS?  Which one?
https://github.com/DrTimothyAldenDavis/SuiteSparse or
https://github.com/DrTimothyAldenDavis/GraphBLAS ?

I have the complex operators in the Demo codes, but not in the main
GraphBLAS library itself.   I think it's a bit early to add complex data
types to GraphBLAS itself. I have to decide if I add complex versions of
just FP32 and FP64, or all the integers, for example.  That will take quite
a bit of work, but it would mean that the complex type would be just as
fast as the other built-in types.  See
https://www.mathworks.com/help/matlab/matlab_external/c-matrix-api-typed-data-access.html
for a complete list.  However, MATLAB only supports arithmetic on floating
point complex values, not integer complex values.  (I guess you can create
complex integers in MATLAB but not do anything with them ??).

Complex floating-point is very important, so I think my first goal would be
to add complex floating-point types, not complex integers.  Complex
integers might be really cool to add to GraphBLAS.  Imagine a graph with
edge weights that are pairs of integers.  I could call them "complex" but a
graph algorithm could use them as just a pair of integers.

Right now, I don't yet support any complex sparse matrices in my MATLAB
interface to GraphBLAS, floating point or integer.  I do use the complex
type in my GraphBLAS/Test framework, but not polished for the world to use
outside of that test framework.  I just use the complex type as an example
user-defined data type, in my tests.

Lots to think about.  For now, I think just adding one complex data type
(complex FP64) to LAGraph is a good start.

**Comment by tgmattso** [comment]
Do we have any use cases where people are interested in graphs with complex edge weights?   It makes sense to me and I can easily imagine they would be needed, but I haven’t heard anyone ask for them.

--Tim

**Comment by DrTimothyAldenDavis** [comment]
I haven't had any requests to add a complex data type yet.  LAGraph has a
Matrix Market file I/O feature, however, and those matrices can be complex
(just floating-point).

My MATLAB interface to GraphBLAS can do anything that MATLAB can do on its
sparse matrices ... except for complex sparse matrices.  So if I had a
GxB_CFP64 type in GraphBLAS (for example), which was built-in, then my
MATLAB interface could easily handle the complex case.  The same would be
true of an Octave interface.  Python libraries like numpy and scipy deal
with complex sparse matrices, and all my sparse solvers handle the complex
case too (some of which are already in numpy or scipy).

So complex matrices are on my radar.  But I don't have any requests for
graph algorithms to use complex sparse matrices.

**Comment by michelp** [comment]
> You mean to SuiteSparse:GraphBLAS? Which one?

Yes.

> Lots to think about.  For now, I think just adding one complex data type
(complex FP64) to LAGraph is a good start.

Sounds good to me, the issues do a seems a bit deeper than just extending LAGraph, so I'll do the rename you suggested and repush here.

**Comment by michelp** [comment]
Renaming is complete, should be ready for final review and merge.

**Pull request merged**
