### PR TITLE
Update Contributors.txt

### PR DESCRIPTION
**Pull request by octopi8314**
suggested change from maw128 to enable shortened headers.

### CODE REVIEW

**Comment by szarnyasg** [comment]
Hi @octopi8314 - the content and the message of this commit do not seem to be in sync. How does this enable shortened headers?

**Comment by octopi8314** [comment]
Putting this statement here will allow CMU/SEI to remove it from individual file header requirements.  (note, there is a stray parenthesis at the end of the line i added that can be deleted).


Thanks,
Michael Wright

**Comment by DrTimothyAldenDavis** [comment]
Michael is referring to the Copyright/Author comments that appear at the top of each source file.  Putting this comment here will allow a terser comment in all the source files.

**Comment by DrTimothyAldenDavis** [comment]
I just deleted the trailing parenthesis, too.

**Pull request merged**
