### PR TITLE
Michelp/linux build v1.1

### PR DESCRIPTION
**Pull request by michelp**

### CODE REVIEW

**Comment by DrTimothyAldenDavis** [comment]
I'm confused ... maybe that's why this is closed.  Don't push anything to stable.  That's LAGraph 1.0.2 and I haven't touched it yet.

**Comment by DrTimothyAldenDavis** [comment]
Only push to stable when it's stable and ready to release as a formal v1.1.0 (not beta).

**Comment by michelp** [comment]
I branched off of your branch and made a PR to trigger the CI, it was just experimental and wasn't meant to be merged.

**Comment by DrTimothyAldenDavis** [comment]
Got it. There's a way to add a manual trigger for the CI. I do that in the suitesparse yaml files. I could try to add it here. It has to be in the default branch though.

**Pull request closed without merging**
