### PR TITLE
Add os config for rtd build.

### PR DESCRIPTION
**Pull request by michelp**

### CODE REVIEW

**Review by DrTimothyAldenDavis — APPROVED** [review]

**Comment by DrTimothyAldenDavis** [comment]
I'll merge it in and we can see if it works. This yaml file is only triggered if it's on the stable branch, I assume?

**Comment by michelp** [comment]
Yep the project is setup for the stable branch, i'll keep my eye on it it hasn't fired off yet but it did fire (and fail) when you made the release yesterday.

**Comment by michelp** [comment]
This is the page to keep an eye on https://readthedocs.org/projects/lagraph/builds/

**Comment by DrTimothyAldenDavis** [comment]
Can it be triggered manually?

**Comment by michelp** [comment]
I'm not seeing a manual trigger option, RTD may be resource limited and take some time getting to the job.

**Pull request merged**
