### PR TITLE
LAGraph v1.0.1

### PR DESCRIPTION
**Pull request by DrTimothyAldenDavis**
Bug fix for LAGraph_MMWrite.  Revising all headers of all files, for additional copyright/license/usage info.

### CODE REVIEW

**Comment by DrTimothyAldenDavis** [comment]
I'd like to include LAGraph v1.0.1 in SuiteSparse v6.0.0.  Can someone review this update?

**Comment by mcmillan03** [comment]
I am confused about the relationship of this branch to stable markings?

Also I think fixing the build problems should be included in the next release but not sure what branch to do that work on.

**Comment by DrTimothyAldenDavis** [comment]
This pull request includes a lot of commits that were made to the dev branch by mistake (they belong to the cuda branch).  The commits have been fixed, by another commit (https://github.com/GraphBLAS/LAGraph/commit/099836bb9e83b631105b99783d90d438bd02478a).

**Review by mcmillan03 — APPROVED** [review]
Reviewed during LAGraph call on 1/11/2023.  Approved.

**Pull request merged**
